AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  LINE multilingual translation bot - serverless stack (Lambda + HTTP API)

Parameters:
  StageName:
    Type: String
    Default: prod
    Description: HTTP API stage name
  FunctionMemorySize:
    Type: Number
    Default: 512
    MinValue: 128
    MaxValue: 10240
    Description: Lambda memory size in MB
  FunctionTimeout:
    Type: Number
    Default: 15
    MinValue: 1
    MaxValue: 29
    Description: Lambda timeout in seconds
  RuntimeSecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret that stores sensitive runtime config (JSON)
  GeminiModel:
    Type: String
    Default: gemini-2.5-flash
    AllowedPattern: ".+"
    Description: Gemini model name
  MaxContextMessages:
    Type: Number
    Default: 20
    MinValue: 1
    MaxValue: 50
    Description: Maximum number of context messages sent to Gemini
  TranslationRetry:
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 5
    Description: Number of Gemini retries

Globals:
  Function:
    Runtime: python3.12
    Handler: src.lambda_handler.lambda_handler
    MemorySize: !Ref FunctionMemorySize
    Timeout: !Ref FunctionTimeout
    Tracing: Active
    Environment:
      Variables:
        LINE_CHANNEL_SECRET: !Sub "{{resolve:secretsmanager:${RuntimeSecretArn}:SecretString:LINE_CHANNEL_SECRET}}"
        LINE_CHANNEL_ACCESS_TOKEN: !Sub "{{resolve:secretsmanager:${RuntimeSecretArn}:SecretString:LINE_CHANNEL_ACCESS_TOKEN}}"
        GEMINI_API_KEY: !Sub "{{resolve:secretsmanager:${RuntimeSecretArn}:SecretString:GEMINI_API_KEY}}"
        NEON_DATABASE_URL: !Sub "{{resolve:secretsmanager:${RuntimeSecretArn}:SecretString:NEON_DATABASE_URL}}"
        GEMINI_MODEL: !Ref GeminiModel
        MAX_CONTEXT_MESSAGES: !Ref MaxContextMessages
        TRANSLATION_RETRY: !Ref TranslationRetry

Resources:
  LineWebhookApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName

  LineWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: Handles LINE webhook events and triggers translation pipeline
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Webhook:
          Type: HttpApi
          Properties:
            ApiId: !Ref LineWebhookApi
            Path: /webhook
            Method: POST

Outputs:
  FunctionArn:
    Description: ARN of the LINE webhook Lambda function
    Value: !GetAtt LineWebhookFunction.Arn
  HttpApiEndpoint:
    Description: Invoke URL for the HTTP API stage
    Value: !Sub "https://${LineWebhookApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
