AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  LINE multilingual translation bot - serverless stack (Lambda + HTTP API)

Parameters:
  StageName:
    Type: String
    Default: prod
    Description: HTTP API stage name
  FunctionMemorySize:
    Type: Number
    Default: 512
    MinValue: 128
    MaxValue: 10240
    Description: Lambda memory size in MB
  FunctionTimeout:
    Type: Number
    Default: 20
    MinValue: 1
    MaxValue: 29
    Description: Lambda timeout in seconds
  RuntimeSecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret that stores sensitive runtime config (JSON)
  GeminiModel:
    Type: String
    Default: gemini-2.5-flash
    AllowedPattern: ".+"
    Description: Gemini model name
  MaxContextMessages:
    Type: Number
    Default: 8
    MinValue: 1
    MaxValue: 50
    Description: Maximum number of context messages sent to Gemini
  TranslationRetry:
    Type: Number
    Default: 2
    MinValue: 1
    MaxValue: 5
    Description: Number of Gemini retries
  MaxGroupLanguages:
    Type: Number
    Default: 5
    MinValue: 1
    MaxValue: 10
    Description: Maximum number of translation target languages per group
  EnableStripe:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    Description: Set to true when Stripe secrets/price IDs are provisioned

Conditions:
  UseStripe: !Equals [!Ref EnableStripe, "true"]

Globals:
  Function:
    Runtime: python3.12
    Handler: src.lambda_handler.lambda_handler
    MemorySize: !Ref FunctionMemorySize
    Timeout: !Ref FunctionTimeout
    Tracing: Active
    Environment:
      Variables:
        LINE_CHANNEL_SECRET: !Sub "{{resolve:secretsmanager:${RuntimeSecretArn}:SecretString:LINE_CHANNEL_SECRET}}"
        LINE_CHANNEL_ACCESS_TOKEN: !Sub "{{resolve:secretsmanager:${RuntimeSecretArn}:SecretString:LINE_CHANNEL_ACCESS_TOKEN}}"
        GEMINI_API_KEY: !Sub "{{resolve:secretsmanager:${RuntimeSecretArn}:SecretString:GEMINI_API_KEY}}"
        NEON_DATABASE_URL: !Sub "{{resolve:secretsmanager:${RuntimeSecretArn}:SecretString:NEON_DATABASE_URL}}"
        GEMINI_MODEL: !Ref GeminiModel
        COMMAND_MODEL: !Ref GeminiModel
        MAX_CONTEXT_MESSAGES: !Ref MaxContextMessages
        MAX_GROUP_LANGUAGES: !Ref MaxGroupLanguages
        TRANSLATION_RETRY: !Ref TranslationRetry
        BOT_MENTION_NAME: !Sub "{{resolve:secretsmanager:${RuntimeSecretArn}:SecretString:BOT_MENTION_NAME}}"
        STRIPE_SECRET_KEY: !If
          - UseStripe
          - !Sub "{{resolve:secretsmanager:${RuntimeSecretArn}:SecretString:STRIPE_SECRET_KEY}}"
          - ""
        STRIPE_WEBHOOK_SECRET: !If
          - UseStripe
          - !Sub "{{resolve:secretsmanager:${RuntimeSecretArn}:SecretString:STRIPE_WEBHOOK_SECRET}}"
          - ""
        STRIPE_PRICE_MONTHLY_ID: !If
          - UseStripe
          - !Sub "{{resolve:secretsmanager:${RuntimeSecretArn}:SecretString:STRIPE_PRICE_MONTHLY_ID}}"
          - ""
        PUBLIC_API_BASE_URL: !Sub "{{resolve:secretsmanager:${RuntimeSecretArn}:SecretString:PUBLIC_API_BASE_URL}}"

Resources:
  LineWebhookApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName

  LineWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: Handles LINE webhook events and triggers translation pipeline
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Webhook:
          Type: HttpApi
          Properties:
            ApiId: !Ref LineWebhookApi
            Path: /webhook
            Method: POST

  StripeWebhookFunction:
    Type: AWS::Serverless::Function
    Condition: UseStripe
    Properties:
      CodeUri: .
      Handler: src.stripe_webhook_handler.lambda_handler
      Description: Handles Stripe webhook events to sync subscription state
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        StripeWebhook:
          Type: HttpApi
          Properties:
            ApiId: !Ref LineWebhookApi
            Path: /stripe/webhook
            Method: POST

  StripeCheckoutRedirectFunction:
    Type: AWS::Serverless::Function
    Condition: UseStripe
    Properties:
      CodeUri: .
      Handler: src.checkout_redirect_handler.lambda_handler
      Description: Issues short checkout redirects for Stripe sessions
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        CheckoutRedirect:
          Type: HttpApi
          Properties:
            ApiId: !Ref LineWebhookApi
            Path: /checkout
            Method: GET

  GroupUsageMonthlyResetFunction:
    Type: AWS::Serverless::Function
    Condition: UseStripe
    Properties:
      CodeUri: .
      Handler: src.usage_counter_initializer.lambda_handler
      Description: Initializes monthly usage counters for each LINE group
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        MonthlySchedule:
          Type: Schedule
          Properties:
            Name: !Sub "group-usage-monthly-reset-${StageName}"
            Description: Monthly counter initializer (00:00 UTC on 1st)
            Schedule: cron(0 0 1 * ? *)

Outputs:
  FunctionArn:
    Description: ARN of the LINE webhook Lambda function
    Value: !GetAtt LineWebhookFunction.Arn
  HttpApiEndpoint:
    Description: Invoke URL for the HTTP API stage
    Value: !Sub "https://${LineWebhookApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
